#!/usr/bin/env php
<?php

/**
 * WPLite CLI - A branding tool for the WPLite WordPress plugin framework
 * 
 * Usage: php wplite install --prefix=MyPlugin
 */

// Ensure we're running from CLI
if (php_sapi_name() !== 'cli') {
    exit('This script must be run from the command line.');
}

// PSR-4 Autoloader for WPLiteCLI namespace
spl_autoload_register(function ($class) {
    $prefix = 'WPLiteCLI\\';
    $baseDir = __DIR__ . '/cli/';

    $len = strlen($prefix);
    if (strncmp($prefix, $class, $len) !== 0) {
        return;
    }

    $relativeClass = substr($class, $len);
    $file = $baseDir . str_replace('\\', '/', $relativeClass) . '.php';

    if (file_exists($file)) {
        require $file;
    }
});

use WPLiteCLI\CommandRunner;

$runner = new CommandRunner($argv);
$runner->run();
